### ISSUE TITLE
Fix the crash

### ISSUE THREAD

**Issue by kovtun1** [foritari/Assignment5#8]
Steps to reproduce:
1. Open the app
2. Create a gallery
3. Select it
4. Drag and drop an image. Wait for it to download
5. Delete the gallery
https://github.com/foritari/Assignment5/blob/8405191cb742b4b4d59fce13cb0114617eabe263/Image%20Gallery/TableView/ImageGalleriesDocumentTableViewController.swift#L122
This line of code crashes the app

**Comment by foritari** [comment]
https://github.com/foritari/Assignment5/pull/10
